name: Yad2 Car Scraper

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing changes back to repository
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Chrome and ChromeDriver
      run: |
        # Install Chrome
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # Verify Chrome installation
        google-chrome --version
        
        # ChromeDriver will be managed by webdriver-manager in Python
    
    - name: Run scraper
      env:
        # Environment Variables (Non-sensitive configuration)
        EMAIL_ENABLED: ${{ vars.EMAIL_ENABLED }}
        EMAIL_SENDER: ${{ vars.EMAIL_SENDER }}
        EMAIL_RECIPIENT: ${{ vars.EMAIL_RECIPIENT }}
        EMAIL_SMTP_SERVER: ${{ vars.EMAIL_SMTP_SERVER }}
        EMAIL_SMTP_PORT: ${{ vars.EMAIL_SMTP_PORT }}
        WHATSAPP_ENABLED: ${{ vars.WHATSAPP_ENABLED }}
        WHATSAPP_PHONE_NUMBER: ${{ vars.WHATSAPP_PHONE_NUMBER }}
        
        # Secrets (Sensitive credentials)
        EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      run: |
        # Run the scraper
        python main.py
    
    - name: Commit and push seen_cars.json if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add seen_cars.json
        git diff --staged --quiet || git commit -m "Update seen_cars.json [skip ci]"
        git push || echo "No changes to push" 
